# Generated by Django 2.0.7 on 2018-08-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_house_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['name'], 'verbose_name': 'тариф', 'verbose_name_plural': 'тарифы'},
        ),
    ]
